### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by bensontrent**
After installing the package I got a 

`npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

This is due to an older glob package requiring that version. 

One of the unit tests was failing due to to an old link to Amazon aws. I chose the next best alternative, which was a similar package on a CDN for the spec test install.

Once unit testing was working, I upgraded the dated package.json dependencies, which caused the unit tests to fail due to a deprecated usage of `_.contains` (now changed to `_.includes`).  

Unit tests all passed.

### CODE REVIEW

**Comment by rquadling** [comment]
I've just pulled this code and ran `npm install` and got ...
```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global jasmine-node@1.14.5 should be installed with -g
bower-installer@1.2.0 /Users/richardquadling/dev/js/bower-installer
├── async@0.2.10  invalid
├── bower@1.8.0 
├── colors@1.1.2 
├─┬ glob@7.1.1 
│ ├── fs.realpath@1.0.0 
│ ├─┬ inflight@1.0.6 
│ │ └── wrappy@1.0.2 
│ ├── inherits@2.0.3 
│ ├─┬ minimatch@3.0.3 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├── once@1.4.0 
│ └── path-is-absolute@1.0.1 
├─┬ grunt@1.0.1 
│ ├── coffee-script@1.10.0 
│ ├─┬ dateformat@1.0.12 
│ │ ├── get-stdin@4.0.1 
│ │ └─┬ meow@3.7.0 
│ │   ├─┬ camelcase-keys@2.1.0 
│ │   │ └── camelcase@2.1.1 
│ │   ├── decamelize@1.2.0 
│ │   ├─┬ loud-rejection@1.6.0 
│ │   │ ├─┬ currently-unhandled@0.4.1 
│ │   │ │ └── array-find-index@1.0.2 
│ │   │ └── signal-exit@3.0.1 
│ │   ├── map-obj@1.0.1 
│ │   ├── minimist@1.2.0 
│ │   ├─┬ normalize-package-data@2.3.5 
│ │   │ ├── hosted-git-info@2.1.5 
│ │   │ ├─┬ is-builtin-module@1.0.0 
│ │   │ │ └── builtin-modules@1.1.1 
│ │   │ ├── semver@5.3.0 
│ │   │ └─┬ validate-npm-package-license@3.0.1 
│ │   │   ├─┬ spdx-correct@1.0.2 
│ │   │   │ └── spdx-license-ids@1.2.2 
│ │   │   └── spdx-expression-parse@1.0.4 
│ │   ├── object-assign@4.1.0 
│ │   ├─┬ read-pkg-up@1.0.1 
│ │   │ ├─┬ find-up@1.1.2 
│ │   │ │ ├── path-exists@2.1.0 
│ │   │ │ └─┬ pinkie-promise@2.0.1 
│ │   │ │   └── pinkie@2.0.4 
│ │   │ └─┬ read-pkg@1.1.0 
│ │   │   ├─┬ load-json-file@1.1.0 
│ │   │   │ ├── graceful-fs@4.1.11 
│ │   │   │ ├─┬ parse-json@2.2.0 
│ │   │   │ │ └─┬ error-ex@1.3.0 
│ │   │   │ │   └── is-arrayish@0.2.1 
│ │   │   │ ├── pify@2.3.0 
│ │   │   │ └─┬ strip-bom@2.0.0 
│ │   │   │   └── is-utf8@0.2.1 
│ │   │   └── path-type@1.1.0 
│ │   ├─┬ redent@1.0.0 
│ │   │ ├─┬ indent-string@2.1.0 
│ │   │ │ └─┬ repeating@2.0.1 
│ │   │ │   └─┬ is-finite@1.0.2 
│ │   │ │     └── number-is-nan@1.0.1 
│ │   │ └── strip-indent@1.0.1 
│ │   └── trim-newlines@1.0.0 
│ ├── eventemitter2@0.4.14 
│ ├── exit@0.1.2 
│ ├─┬ findup-sync@0.3.0 
│ │ └── glob@5.0.15 
│ ├── glob@7.0.6 
│ ├─┬ grunt-cli@1.2.0 
│ │ └── resolve@1.1.7 
│ ├── grunt-known-options@1.1.0 
│ ├─┬ grunt-legacy-log@1.0.0 
│ │ ├─┬ grunt-legacy-log-utils@1.0.0 
│ │ │ ├─┬ chalk@1.1.3 
│ │ │ │ ├── ansi-styles@2.2.1 
│ │ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ │ └── ansi-regex@2.0.0 
│ │ │ │ ├── strip-ansi@3.0.1 
│ │ │ │ └── supports-color@2.0.0 
│ │ │ └── lodash@4.3.0 
│ │ ├── hooker@0.2.3 
│ │ ├── lodash@3.10.1 
│ │ └── underscore.string@3.2.3 
│ ├─┬ grunt-legacy-util@1.0.0 
│ │ ├── async@1.5.2 
│ │ ├── getobject@0.1.0 
│ │ ├── lodash@4.3.0 
│ │ └─┬ which@1.2.12 
│ │   └── isexe@1.1.2 
│ ├── iconv-lite@0.4.15 
│ ├─┬ js-yaml@3.5.5 
│ │ ├─┬ argparse@1.0.9 
│ │ │ └── sprintf-js@1.0.3 
│ │ └── esprima@2.7.3 
│ └── rimraf@2.2.8 
├─┬ grunt-jasmine-node@0.3.1 
│ ├── coffee-script@1.6.3 
│ └─┬ jasmine-node@1.14.5 
│   ├─┬ gaze@0.3.4 
│   │ ├─┬ fileset@0.1.8 
│   │ │ ├─┬ glob@3.2.11 
│   │ │ │ └── minimatch@0.3.0 
│   │ │ └── minimatch@0.4.0 
│   │ └─┬ minimatch@0.2.14 
│   │   ├── lru-cache@2.7.3 
│   │   └── sigmund@1.0.1 
│   ├─┬ jasmine-growl-reporter@0.0.3 
│   │ └── growl@1.7.0 
│   ├─┬ jasmine-reporters@1.0.2 
│   │ └── mkdirp@0.3.5 
│   ├── mkdirp@0.3.5 
│   ├── requirejs@2.3.2 
│   ├── underscore@1.8.3 
│   └── walkdir@0.0.11 
├── lodash@4.17.2 
├─┬ mkdirp@0.5.1 
│ └── minimist@0.0.8 
├── node-fs@0.1.7 
├─┬ nopt@3.0.6 
│ └── abbrev@1.0.9 
└── rimraf@2.5.4 

npm WARN bower-installer@1.2.0 license should be a valid SPDX license expression
```

I'm not a JS/node expert, but if you can help me understand what has been fixed (or what I've done wrong), then I can get this merged.

**Comment by bensontrent** [comment]
Ok, I fixed the issues; I wasn't seeing those warnings because I had tested with `npm install --global` and the devDependencies aren't installed there, which is why I didn't see those warnings when using `npm install path/to/my/local/bower-installer -D` 
I removed the source of the minimatch errors-- grunt-jasmine-node is a dead project that hasn't been updated in some time.  So I've replaced that with the simpler jasmine cli tool.  

### Changes made to remove errors shown at `npm install`:  

* Replaced grunt-jasmine-node with jasmine
  - This dated project had an unsafe version of minimatch
  - Added Configuration file for command-line version of Jasmine
  - Used the CLI interface in the package.json for jasmine. Test can be run using `npm test`
* BSD License corrected to MIT license to prevent install warnings and to reflect the actual license in LICENSE.md. BSD is not a valid license type; `BSD-3-Clause-Clear` or `BSD-2-Clause` could be an alternative.  See more options at http://choosealicense.com/appendix/
* Ran `npm init` 
   -Rerunning this command on an old project can fix formating and syntax errors, many of which were fixed.

**Comment by rquadling** [comment]
Hi.

Can you rebase your changes off master and I'll get them merged.

Thank you for your efforts.

**Comment by bensontrent** [comment]
That is the last commit.  I'm sorry for the number of commits, our local system is setup for abundant history. Webstorm did an automated process.  If you have a need to reduce this history here I can close this pull request and squash everything to one commit, based off the latest master.

**Comment by rquadling** [comment]
I can squash it in GitHub.

**Comment by rquadling** [comment]
Ha! Closed by mistake.

**Comment by rquadling** [comment]
Getting an issue on merging for a submodule typings?

**Comment by bensontrent** [comment]
I'll do a pull and see what's up. I wouldn't expect Typings to be
associated with the project.

**Comment by rquadling** [comment]
https://github.com/rquadling/bower-installer/pull/158/files#diff-4419bad7f25fd13106e6fe7516df7617

I think it must be a carry over from your end.

I've removed it, ran the tests locally (initially had a timeout as I guess a LOT of packages needed to be loaded/verified/etc.)

Second test run ... all OK.

**Comment by bensontrent** [comment]
Ok all good. Not sure how that folder ended up in the package but it's
removed on my end now as well. Thanks!

**Pull request merged**
