### PR TITLE
Better error handling when loading configuration files

### PR DESCRIPTION
**Pull request by chaitan94**
I believe this addresses the issue #107

### CODE REVIEW

**Comment by rquadling** [comment]
Hi.

Can you rebase your changes off master and I'll get them merged.

Thank you for your efforts.

**Comment by rquadling** [comment]
BTW, I'm the new project owner, so hopefully things will move forward now.

**Comment by chaitan94** [comment]
I've rebased the commit.

**Comment by rquadling** [comment]
2 similar PRs. Thank you.

**Pull request closed without merging**
